<div class="container">
    <div class="row">

        <div class="col-lg-12">
        <div class="market-reports">

            <div class="container" style="padding-left: 0px; padding-right: 0px;">
                <div class="header-container">
                  
                  <div class="row">

                    <div class="col-lg-6 col-md-12">
                      <h1 class="header-36">
                        <?php echo get_the_title(); ?>
                      </h1>
                      <div class="line"></div>

                      <a class="inside-back" href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                        <button  class="inside-back-btn">
                          <img class="back-icon" src="<?php echo get_stylesheet_directory_uri(); ?>/assets/img/back.png">
                          <span class="back-text">Back</span>
                        </button>
                      </a>

                    </div>

                    <div class="col-lg-6 col-md-12">
                      <div class="tab-panel inside-drop-area fade show active" id="events-tab-content" role="tabpanel">
                          <div class="row">
                                  <div class="col-md-12">
                                    <div class="inside-drop-content" id="reports-filters">
                                      <select class="inside-select-category inside-sort sort-reports mr-select" id="sort" name="Year" required="">
                                        <option value="published_date DESC" selected="selected" style="">Sort</option>
                                        <option value="published_date DESC">By Date: Descending</option>
                                        <option value="published_date ASC">By Date: Ascending</option>
                                        <option value="doc_title ASC">Alphabetical: A-Z</option>
                                        <option value="doc_title DESC">Alphabetical: Z-A</option>
                                      </select>

                                      <input type="text" name="datefilter" id="md-date-filter" placeholder="Select Date" class="inside-select-category inside-date-picker mr-select" readonly=""> 

                                    </div>
                                  </div>
                          </div>
                    </div>

                    </div>
                  </div>

                </div>

                    <!-- Tab Panel -->
                    
            </div>
            
            <div class="market-reports-group-title"><?php echo $cat_name; ?></div>
            <div id="market-data-loader"><i class="fa fa-spinner fa-spin fa-3x" aria-hidden="true"></i></div>
            <div id="market-data-cont">
                <div class="market-reports-group">
                    <div class="row" id="list-cont">
                        <!-- files here generated by ajax -->
                    </div>
                </div>
            </div>
            <div class="center" style="margin-top: 30px;">
                <div id="pagination-container" class="linear-pagination"></div>
            </div>
        </div>
        </div>


       

</div>
</div>