<div class="container">
    <div class="row">

            <div class="col-lg-12">
            <div class="market-reports">

                <div class="container" style="padding-left: 0px; padding-right: 0px;">
                    <div class="header-container">
                      
                      <div class="row">

                        <div class="col-lg-6 col-md-12">
                          <h1 class="header-36">
                                <?php echo get_the_title(); ?>
                          </h1> 
                          <div class="line"></div>

                          <a class="inside-back" href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                            <button  class="inside-back-btn">
                              <img class="back-icon" src="<?php echo get_stylesheet_directory_uri();?>/assets/img/back.png">
                              <span class="back-text">Back</span>
                            </button>
                          </a>

                        </div>
                        <?php
                        if($files){ ?>
                            <div class="col-lg-6 col-md-12">
                              <div class="tab-panel inside-drop-area fade show active" id="events-tab-content" role="tabpanel">
                                  <div class="row">
                                         <!--  <div class="col-md-7 col-12">
                                          </div> -->
                                        
                                          <div class="col-md-12">
                                            <div class="inside-drop-content">
                                              <select class="inside-select-category inside-sort" id="sort" name="Year" required="">
                                                <option value="" selected="selected" style="">Sort by Date</option>
                                                <option value="asc">Ascending</option>
                                                <option value="desc">Descending</option>
                                              </select>
                                              
                                              <input type="text" name="datefilter" id="md-date-filter" placeholder="Select Date" class="inside-select-category inside-date-picker" readonly="">
                                                <!-- <div id="dl-all-btn-cont"> -->
                                                    <a href="?post=<?php echo $post->ID; ?>&sort=desc&page=1&start=&end=" id="dl-all-btn" >
                                                      <button class="inside-download-area">
                                                          <img class="inside-download-icon" src="<?php echo get_stylesheet_directory_uri(); ?>/assets/img/inside-download.png">
                                                      </button>
                                                        
                                                    </a>
                                                <!-- </div> -->
                                                

                                            </div>
                                          </div>
                                  </div>
                            </div><?php
                        } ?>

                        </div>
                      </div>

                    </div>

                        <!-- Tab Panel -->
                        
                </div>
                <div id="market-data-loader"><i class="fa fa-spinner fa-spin fa-3x" aria-hidden="true"></i></div>
                <div id="market-data-cont">
                    <div class="market-reports-group">

                        <div class="row" id="list-cont">
                            <!-- files here generated by ajax -->
                        </div>
                    </div>
                    
                </div>
                <div class="center" style="margin-top: 30px;">
                    <div id="pagination-container" class="linear-pagination"></div>
                </div>
                



            </div>
            </div>


           

    </div>
</div>